### ISSUE TITLE
Add hub.docker.com as a provider

### ISSUE THREAD

**Issue by matipan** [marcosnils/bin#1]
# Description
CLIs are sometimes provided as docker images and allow users to use the CLI without having to worry about installing the binary correct for their architecture.

# Usability
Users of bin should be able to install docker images that represent CLIs if they were a regular binary that needs to be downloaded:
```
bin install hub.docker.com/r/hashicorp/terraform
terraform init
```

**Comment by marcosnils** [comment]
Just checked the the docker provider and it seems like it's very tied to dockerhub. How about if we change it to be able to pull from any registry?

The proposed UI could be: 

```
bin install docker://hashicorp/terraform # installs from dockerhub by defailt
bin install docker://quay.io/calico/node # installs from quay.io registry
```

This way we can use the short image syntax and parsing the provider is simpler since we can use the `docker://` schema. 

Thoughts?

**Comment by matipan** [comment]
I like the idea of having `docker://`. One of the things I was struggling with was making everything agnostic to the provider. Its implemented agnostic but the only supported URLs are hub.docker.com and docker.io. The change should be minimal.

I assume we want versioning of the images?

**Comment by marcosnils** [comment]
> I assume we want versioning of the images?

Correct. you should be able to specify a tag of an image as well. We'd need to think how the `bin update` since if you pin an image to a specific version.. it'd a be a bit tricky to decide when to update.

**Comment by matipan** [comment]
Exactly. And the "get latest version" method is also a bit tricky since I imagine each registry API has its own way of fetching all tags. Or is there a standard that all registries implement?
