### ISSUE TITLE
Implement version pinning

### ISSUE THREAD

**Issue by sphr2k** [marcosnils/bin#126]
It would be great if we could pin versions for apps such as terraform, kubectl or istioctl, where often, it is not desirable to install the latest version.

**Comment by marcosnils** [comment]
good idea, and I also thing it's useful. I'll craft something this week

**Comment by pwillis-eiq** [comment]
Hey @marcosnils , I finally have an excuse to work on this :D did you do any code related to this or should I start from scratch?

**Comment by peterwwillis** [comment]
Hi @marcosnils , I think I have some time to work on this now :D Have you done any work on this yet?

**Comment by marcosnils** [comment]
haven't done any progress unfortunately. Feel free to give it a try. LMK if you need any input from my side :pray:

**Comment by snwzt** [comment]
Hi @marcosnils, I've put together a simple implementation of version pinning on [my fork](https://github.com/snwzt/bin). Where can I improve? (After that I'll make a PR)

**Comment by marcosnils** [comment]
Hey @snwzt, thx for sharing! I'd go ahead and open a PR as-is so we can start the conversations there. You can open the PR in draft mode also to emphasize that it's not review ready.
