### ISSUE TITLE
bin install github.com/helm/helm

### ISSUE THREAD

**Issue by dR3b** [marcosnils/bin#127]
I got the following error with `bin install github.com/helm/helm`:
```bash
% bin install github.com/helm/helm
   • Getting latest release for helm/helm

Multiple matches found, please select one:

 [1] 54827640
 [2] 54827642
 [3] 54827644
 [4] 54827645
 [5] 54827647
 [6] 54827648
 Select an option: ^C
```
I would expect the versions x.y.z. here.

**Comment by marcosnils** [comment]
Fixed in `bin` v0.13.1. 

Unfortunately, `helm` cannot be installed using `bin` because they don't publish their binaries in github releases.

**Comment by dR3b** [comment]
Alternatives?

**Comment by marcosnils** [comment]
Use any of their official package manager releases? https://helm.sh/

**Comment by MurzNN** [comment]
Seems this will be possible when this PR https://github.com/marcosnils/bin/pull/179 will be merged, and for `kubectl` too?

**Comment by marcosnils** [comment]
> Seems this will be possible when this PR #179 will be merged, and for `kubectl` too?

yes, this seems to be possible.
