### ISSUE TITLE
Add GitLab provider

### ISSUE THREAD

**Issue by sirlatrom** [marcosnils/bin#14]
I started working on a GitLab provider but failed when I got to the point of actually downloading the binary from a _private_ project. Turns out they don't have the same access control on release assets as on the rest of their API.

I created this issue on GitLab and when/if it gets resolved I will open a PR for GitLab if that is welcome.

https://gitlab.com/gitlab-org/gitlab/-/issues/232704

**Comment by marcosnils** [comment]
Interesting.. how about public releases? Can we have something for that to start with?

**Comment by sirlatrom** [comment]
> 
> 
> Interesting.. how about public releases? Can we have something for that to start with?

Looks like it yes, so I guess I can submit the PR with the caveat that it won't work for private repos just yet. Can add a check for the login redirect status code (302) that you get on non-public projects to give a better error message. Come to think of it either the status code isn't checked or 302 is considered not an error type of status, i.e. <400.

**Comment by sirlatrom** [comment]
Example of a release on GitLab: https://gitlab.com/gitlab-org/gitlab-runner/-/releases/v13.2.1

Not very friendly resource names - in this case the basename of the URL path (e.g. linux amd64 => `gitlab-runner-linux-amd64`) is actually better for guessing the binary name. Is this a case I should consider while adding this PR?

**Comment by sirlatrom** [comment]
> 
> 
> Example of a release on GitLab: https://gitlab.com/gitlab-org/gitlab-runner/-/releases/v13.2.1
> 
> Not very friendly resource names - in this case the basename of the URL path (e.g. linux amd64 => `gitlab-runner-linux-amd64`) is actually better for guessing the binary name. Is this a case I should consider while adding this PR?

I've done it as described above in the PR.

**Comment by marcosnils** [comment]
> Not very friendly resource names - in this case the basename of the URL path (e.g. linux amd64 => `gitlab-runner-linux-amd64`) is actually better for guessing the binary name. Is this a case I should consider while adding this PR?

Hmm do we want to do this?? I've just checked and seems like the runners repo is actually messing up with release names. 

If you check this other repo (https://gitlab.com/graphviz/graphviz/-/releases) the release name is correct and the URL is garbage.. I think the best thing is to use the release name as it should be. If the release name is garbage, the bin user always has the decision to manually change it when installing something.

**Comment by sirlatrom** [comment]
> Hmm do we want to do this?? I've just checked and seems like the runners repo is actually messing up with release names.
> 

I agree it doesn't look pretty even though making it look pretty is probably why they did that. However, the URLs follow a more reasonable scheme: `https://gitlab-runner-downloads.s3.amazonaws.com/v13.2.1/binaries/gitlab-runner-linux-amd64`. Note the external hosting on amazonaws.com.

Before accommodating this type of release, I would instead get a binary called "linux amd64" due to the release asset link's name. Even if we sanitized away the OS and Arch, we'd end up with an empty string, which is also not optimal.

> If you check this other repo (https://gitlab.com/graphviz/graphviz/-/releases) the release name is correct and the URL is garbage.. I think the best thing is to use the release name as it should be. If the release name is garbage, the bin user always has the decision to manually change it when installing something.

In the case of graphviz they only release the source archives, but unfortunately not any binaries, so even though they have a nicely formatted URL they don't have anything for us to download.

**Comment by marcosnils** [comment]
> In the case of graphviz they only release the source archives, but unfortunately not any binaries, so even though they have a nicely formatted URL they don't have anything for us to download.

You're correct, I got confused with the "Evidence collection" thing.

If you look this other project instead (https://gitlab.com/CalcProgrammer1/OpenRGB/-/releases) the binaries are properly formatted. 

What I'm trying to say is that it's up to the project owner to name the binaries correctly when they release them. I'm not sure why the `gitlab-runner` team has decided to use those awful names but what it resonates to me is that when you use `bin` the binary name will be the one used in the URL instead of the one that you see in the releases page. 

IDK.. I still don't have a strong opinion about this. Since it's the first gitlab provider I guess we can move forward with this approach and see how it evolves in the future and if it needs to be improved. After all, the idea of `bin` is to try to work out of the box.. so let's keep it that way :muscle:
