### ISSUE TITLE
Repository says there's no release even though there is?

### ISSUE THREAD

**Issue by skorokithakis** [marcosnils/bin#143]
I'm not sure if I'm doing something wrong, but in https://github.com/martinvonz/jj I see releases, but running `bin` says it doesn't find any. Am I being dumb?

**Comment by marcosnils** [comment]
:wave: here's the reason: https://github.com/marcosnils/bin#i-see-releases-on-github-but-bin-does-not-pick-them-up

**Comment by skorokithakis** [comment]
Ahh, sorry, I saw that but didn't realise they were all prereleases. Thank you.
