### ISSUE TITLE
[Request] Additonal installation method

### ISSUE THREAD

**Issue by joe733** [marcosnils/bin#164]
I've created an [`asdf`](https://asdf-vm.com) plugin [`asdf-bin`](https://github.com/joe733/asdf-bin), which can help install multiple versions of `bin`, which developers might find very handy. So, in the [installation section of the `README.md`](https://github.com/marcosnils/bin#installing), as an alternate/unofficial method you can add the possibility of installing `bin` using `asdf`.

```markdown
## Installing

1. Download bin from the [releases](https://github.com/marcosnils/bin/releases)
2. Run ./bin install github.com/marcosnils/bin so bin is managed by bin itself
3. Run bin ls to make sure bin has been installed correctly. You can now remove the first file you downloaded.
4. Enjoy!

### Alternatively ...

If you're an [`asdf`](https://asdf-vm.com) user, you can simply follow these steps:

  ```console
  $ asdf plugin add bin
  $ asdf install bin latest
  $ asdf global bin latest
  $ bin --version
  bin version 0.16.2
  commit: d1213c11e63483174ed95308c9eb6372bb9b16e9
  built at: 2023-02-21T13:11:19Z
  built by: goreleaser
  .```
```

**Comment by marcosnils** [comment]
has it been a request for this? It shouldn't make a lot of sense for `bin` users to have multiple version of it. 

I prefer no to merge this unless there's a clear need from more users. Thx for the kind request!

**Comment by dfang** [comment]
If you want have multiple versions of `bin`, you can check `rtx` or `asdf`.

```
rtx plugin add bin https://github.com/joe733/asdf-bin.git
rtx ls-remote bin
rtx i bin@latest
```
