### ISSUE TITLE
Idea: HashiCorp provider

### ISSUE THREAD

**Issue by sirlatrom** [marcosnils/bin#20]
HashiCorp releases many tools that a developer might want to have locally, e.g. `terraform`, `consul`, `vault`, etc.

They have a JSON API: https://releases.hashicorp.com/index.json

So it could be more or less straightforward to build a provider, though maybe it's a little too niche? What do you think?

**Comment by sirlatrom** [comment]
Example of Terraform version 0.12.29:

> ```json
> {
>     "name": "terraform",
>     "version": "0.12.29",
>     "shasums": "terraform_0.12.29_SHA256SUMS",
>     "shasums_signature": "terraform_0.12.29_SHA256SUMS.sig",
>     "builds": [
>         { "name": "terraform", "version": "0.12.29", "os": "darwin", "arch": "amd64", "filename": "terraform_0.12.29_darwin_amd64.zip", "url": "https://releases.hashicorp.com/terraform/0.12.29/terraform_0.12.29_darwin_amd64.zip" },
>         { "name": "terraform", "version": "0.12.29", "os": "freebsd", "arch": "386", "filename": "terraform_0.12.29_freebsd_386.zip", "url": "https://releases.hashicorp.com/terraform/0.12.29/terraform_0.12.29_freebsd_386.zip" },
>         { "name": "terraform", "version": "0.12.29", "os": "freebsd", "arch": "amd64", "filename": "terraform_0.12.29_freebsd_amd64.zip", "url": "https://releases.hashicorp.com/terraform/0.12.29/terraform_0.12.29_freebsd_amd64.zip" },
>         { "name": "terraform", "version": "0.12.29", "os": "freebsd", "arch": "arm", "filename": "terraform_0.12.29_freebsd_arm.zip", "url": "https://releases.hashicorp.com/terraform/0.12.29/terraform_0.12.29_freebsd_arm.zip" },
>         { "name": "terraform", "version": "0.12.29", "os": "linux", "arch": "386", "filename": "terraform_0.12.29_linux_386.zip", "url": "https://releases.hashicorp.com/terraform/0.12.29/terraform_0.12.29_linux_386.zip" },
>         { "name": "terraform", "version": "0.12.29", "os": "linux", "arch": "amd64", "filename": "terraform_0.12.29_linux_amd64.zip", "url": "https://releases.hashicorp.com/terraform/0.12.29/terraform_0.12.29_linux_amd64.zip" },
>         { "name": "terraform", "version": "0.12.29", "os": "linux", "arch": "arm", "filename": "terraform_0.12.29_linux_arm.zip", "url": "https://releases.hashicorp.com/terraform/0.12.29/terraform_0.12.29_linux_arm.zip" },
>         { "name": "terraform", "version": "0.12.29", "os": "openbsd", "arch": "386", "filename": "terraform_0.12.29_openbsd_386.zip", "url": "https://releases.hashicorp.com/terraform/0.12.29/terraform_0.12.29_openbsd_386.zip" },
>         { "name": "terraform", "version": "0.12.29", "os": "openbsd", "arch": "amd64", "filename": "terraform_0.12.29_openbsd_amd64.zip", "url": "https://releases.hashicorp.com/terraform/0.12.29/terraform_0.12.29_openbsd_amd64.zip" },
>         { "name": "terraform", "version": "0.12.29", "os": "solaris", "arch": "amd64", "filename": "terraform_0.12.29_solaris_amd64.zip", "url": "https://releases.hashicorp.com/terraform/0.12.29/terraform_0.12.29_solaris_amd64.zip" },
>         { "name": "terraform", "version": "0.12.29", "os": "windows", "arch": "386", "filename": "terraform_0.12.29_windows_386.zip", "url": "https://releases.hashicorp.com/terraform/0.12.29/terraform_0.12.29_windows_386.zip" },
>         { "name": "terraform", "version": "0.12.29", "os": "windows", "arch": "amd64", "filename": "terraform_0.12.29_windows_amd64.zip", "url": "https://releases.hashicorp.com/terraform/0.12.29/terraform_0.12.29_windows_amd64.zip" }
>     ]
> }
> ```

**Comment by marcosnils** [comment]
> So it could be more or less straightforward to build a provider, though maybe it's a little too niche? What do you think?

I do believe it's a bit niche.. but if you find it useful and you want to include it, I'm happy to review and merge. I'll probably use it eventually
