### ISSUE TITLE
Ensure installed binary versions are matching config file

### ISSUE THREAD

**Issue by einarpersson** [marcosnils/bin#204]
## Context: 
I really love this tool. I have started to migrate many binaries to use bin on my laptop. Now I want to share the same configuration file (in my dotfiles repo) with my home server. But I am struggling with how to keep them in sync, for example after updating (and pushing the changed config) on one computer, how can I then _ensure_ the installed tools are of the same version on the other? I want to pull the latest changes which updates my bin config, and at time the config and reality does not match. But if I run `bin ensure` or `bin update -a` nothing happens.

**What I am missing is something like:**
`bin ensure --version` that both looks at IF the tools is there, and IF it has a matching version. And if not, the user can then go ahead and update it. **Actually, i'd prefer if `bin ensure` by default also checks version**, and perhaps has a flag `--ignore-version`.

I would like a workflow like this:
1. Computer A: `bin update foo`
2. Computer A: git add, commit, push xyz
3. Computer B: git pull xyz
4. Computer B: `bin ensure` (updates/reinstalls binary foo of matching version, given what is specified in config)

Today as far as I can tell, the fourth step would just say nothing, indicating that everything is fine. And if I run `bin update -a` it would say that everything is up to date, since the config is up to date (but the actual installed tool is out of date, not matching the config). 

thanks again for this fantastic tool

**Comment by marcosnils** [comment]
> I want to pull the latest changes which updates my bin config, and at time the config and reality does not match. But if I run `bin ensure` or `bin update -a` nothing happens.

I think this is a missing feature of `bin ensure`. It currently only checks if the binaries exist but it doesn't verify the version. I've opened an issue to implement this: https://github.com/marcosnils/bin/issues/205

**Comment by marcosnils** [comment]
closed in favor of #205
