### ISSUE TITLE
deb instead of appimage

### ISSUE THREAD

**Issue by h434ni** [marcosnils/bin#217]
it installs appimage instead of .deb

**Comment by marcosnils** [comment]
? not sure I follow

**Comment by h434ni** [comment]
oh sorry
on a debian based machine, the program chooses the appimage version while there is also a .deb version available in the release section

**Comment by marcosnils** [comment]
> on a debian based machine, the program chooses the appimage version while there is also a .deb version available in the release section

 this is somehow expected given that `bin` is not built to handle `.deb` files.

**Comment by h434ni** [comment]
so bin is unable to install .Deb files? are you planning to add it any time soon?

-------- Original Message --------

**Comment by marcosnils** [comment]
> so bin is unable to install .Deb files? are you planning to add it any time soon?

 yes, bin is unable to install binary files for the moment.There are no plans to add this feature soon since `bin` has been designed mostly for binary files. If there's enough demand, I could revisit in the future.
