### ISSUE TITLE
Remove incorrectly downloaded binaries

### ISSUE THREAD

**Issue by marcosnils** [marcosnils/bin#23]
If download gets interrupted somehow (cmd + c or whatever), a corrupted file will be created in the FS. 

We should probably download the file to a tmp dir and then move it to the final path once finished.

**Comment by sirlatrom** [comment]
Since we download the binary or archive to memory first since #29, maybe this isn't an issue any longer?

**Comment by marcosnils** [comment]
Makes sense.
