### ISSUE TITLE
Refactor archive recognition

### ISSUE THREAD

**Issue by sirlatrom** [marcosnils/bin#24]
Currently each provider's Fetch function deal with archives on their own, i.e. they test for specific expected archive types which seems redundant.

**Comment by sirlatrom** [comment]
For .xz archives we could consider https://github.com/xi2/xz

**Comment by marcosnils** [comment]
> Currently each provider's Fetch function deal with archives on their own, i.e. they test for specific expected archive types which seems redundant.

Correct.. one of the reason that I decided to put all the providers in the same package is so we can reuse functions like asset filtering and matching. It's definitely worth to revisit.

**Comment by marcosnils** [comment]
> For .xz archives we could consider https://github.com/xi2/xz

:muscle:
