### ISSUE TITLE
Problem with container accepting stdin data

### ISSUE THREAD

**Issue by pammacdotnet** [marcosnils/bin#33]
Hi, I have tried to have running the tool described here:
https://www.attosol.com/using-docker-for-distributing-command-line-tools/

The install works fine: 
$ bin install docker://attosol/dot2png

… but the utility can't be executed as described in the aforementioned article:
$ cat file.dot | dot2png > file.png
the input device is not a TTY

If called as described, it works fine:
$ cat file.dot | docker run --rm -i attosol/dot2png > file.png

Perhaps the problem is that there is no standard for executing dockerized command line tools (?)

Thanks in advance…

**Comment by marcosnils** [comment]
@pammacdotnet thx for reporting this. I've just opened #34 that should fix this. Mind trying it out and provide feedback so we can merge? 
Thx!.

**Comment by pammacdotnet** [comment]
Sure @marcosnils! Yes! I'll keep an eye on this. However, could you please provide minimal compilation-from-source instructions in the main README.md file (3-4 lines)? I know Go is an easy language and development environment, but I'm no expert in this specific field. I'd like to help by compiling and testing the `check_stdin_tty` branch, but some minimal guidelines would be much appreciated. Thanks in advance.
