### ISSUE TITLE
Bad arch

### ISSUE THREAD

**Issue by castorinop** [marcosnils/bin#36]
i try install Cura on Linux x86_64 
 
```
 bin install https://github.com/Ultimaker/Cura --debug  
   • debug logs enabled       
   • Download path set to /home/pablo/bin
   • Getting latest release for Ultimaker/Cura
   • Keeping ultimaker_cura-4.7.1-win64.msi (URL https://github.com/Ultimaker/Cura/releases/download/4.7.1/Ultimaker_Cura-4.7.1-win64.msi) with highest score 10
   • Checking binary from https://github.com/Ultimaker/Cura/releases/download/4.7.1/Ultimaker_Cura-4.7.1-win64.msi
   • Starting download of https://github.com/Ultimaker/Cura/releases/download/4.7.1/Ultimaker_Cura-4.7.1-win64.msi
```
Cura does not provide x86_64, instead it provides Appimage.

Expected: 
- if not exist release for your arch and are available AppImage ask if install this.   
- dont install win64 on Linux.

**Comment by sirlatrom** [comment]
Is an AppImage a single executable binary?

**Comment by marcosnils** [comment]
> Is an AppImage a single executable binary?

yes

```
$ file Ultimaker_Cura-4.8.0.AppImage 
Ultimaker_Cura-4.8.0.AppImage: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.18, stripped
```

> Expected:
> 
> * if not exist release for your arch and are available AppImage ask if install this.
> * dont install win64 on Linux.

I guess this definitely makes sense, so we should score `.AppImage` files higher. One thing to consider though is that AppImage is still CPU architecture dependent. In the case of CURA, it doesn't specify which arch the artifact is for, I'd assume is x86_64.

**Comment by sirlatrom** [comment]
> In the case of CURA, it doesn't specify which arch the artifact is for, I'd assume is x86_64.

Since there is now a `.exe` matcher since #46, and with AppImage being Linux-only, we could:

 - Add an AppImage file extension matcher so it will be considered at all, and
 - Consider adding another dimension when filtering assets, e.g. "OS extensions", which would make an `.AppImage` file score higher on Linux, and an `.exe` file score higher on Windows.
