### ISSUE TITLE
hashicorp provider doesn't work with vault

### ISSUE THREAD

**Issue by jqueuniet** [marcosnils/bin#38]
```
❯ bin install --debug https://releases.hashicorp.com/vault
   • debug logs enabled       
   • Download path set to /home/johann/bin
   • Getting latest release for vault
   ⨯ command failed            error=strconv.ParseInt: parsing "5.1": invalid syntax
```

Other Hashicorp binaries like terraform, consul, packer or nomad seem to work fine.

**Comment by szaffarano** [comment]
The problem is because at least this hashicorp repo has some versions that aren't semver compliant, for example `1.2.6.1+ent`.  This causes an error while [parsing the version](https://github.com/marcosnils/bin/blob/master/pkg/providers/hashicorp.go#L140).
Should it be silently ignored?

**Comment by marcosnils** [comment]
cc @sirlatrom

**Comment by sirlatrom** [comment]
I can verify that it's because of versions like this one:

```
{"name":"vault","version":"1.5.2.1+ent","shasums":"vault_1.5.2.1+ent_SHA256SUMS","shasums_signature":"vault_1.5.2.1+ent_SHA256SUMS.sig","builds":[{"name":"vault","version":"1.5.2.1+ent","os":"darwin","arch":"386","filename":"vault_1.5.2.1+ent_darwin_386.zip","url":"https://releases.hashicorp.com/vault/1.5.2.1+ent/vault_1.5.2.1+ent_darwin_386.zip"},
```
https://releases.hashicorp.com/vault/index.json

I'll see if I can think of a reasonable workaround...
