### ISSUE TITLE
Feature Request: Asset search

### ISSUE THREAD

**Issue by oed-mertenss** [marcosnils/bin#39]
Hello,

i really like your project :)
It would be nice if it is possible to specify the binary that i want to download from a group of release assets.

e.g.:
https://github.com/CrunchyData/postgres-operator/releases
There are some assets:
```
pgo
pgo-bash-completion
...
postgres-operator.4.5.0.tar.gz
```

That want i want is just to install pgo and pgo-bash-completion.

What do you think of a new cli flag called `--regex-search`

`bin install https://github.com/CrunchyData/postgres-operator --regex-search "^pgo$" ~/.local/bin/pgo`
`bin install https://github.com/CrunchyData/postgres-operator --regex-search "^pgo-bash" ~/.local/completions/pgo-bash-completion`

Best regards

Stefan

**Comment by oed-mertenss** [comment]
Bump.
Still when i do: "bin install https://github.com/CrunchyData/postgres-operator/" i get the tar file instead of the binary i want.

**Comment by sirlatrom** [comment]
> 
> 
> Bump.
> Still when i do: "bin install https://github.com/CrunchyData/postgres-operator/" i get the tar file instead of the binary i want.

That is because the repository in question does not name their release assets in a helpful way. I recommend you raise this issue in that particular repo.

**Comment by marcosnils** [comment]
> It would be nice if it is possible to specify the binary that i want to download from a group of release assets.

I think this use-case might still be valid though. Maybe instead of doing something like `--regex-search` we can just add a `--no-score` flag or something similar so the user gets prompted with binary to download. WDYT @sirlatrom @breml ?

**Comment by sirlatrom** [comment]
> > It would be nice if it is possible to specify the binary that i want to download from a group of release assets.
> 
> I think this use-case might still be valid though. Maybe instead of doing something like `--regex-search` we can just add a `--no-score` flag or something similar so the user gets prompted with binary to download. WDYT @sirlatrom @breml ?

Maybe something like `--no-filter`?

**Comment by marcosnils** [comment]
> Maybe something like `--no-filter`?

Yep, that sounds better. Since scoring is an internal implementation detail.
