### ISSUE TITLE
Allow to update binaries using only the binary name

### ISSUE THREAD

**Issue by marcosnils** [marcosnils/bin#43]
The way I'm currently updating single binaries is by doing `bin update $(which <program>)`. Even though it's quite nice, I think the UX can be improved by just doing `bin update <program>`. This shouldn't be difficult to do since the [update](https://github.com/marcosnils/bin/blob/master/cmd/update.go#L26) command could perform this check automatically.

**Comment by cristiand391** [comment]
This seems to be resolved in #44.

I would like to be able to remove binaries by name too, any interest in a PR?

**Comment by marcosnils** [comment]
> I would like to be able to remove binaries by name too, any interest in a PR?

Yep, makes sense to allow this as well. Let's make sure to re-use the code from update and delete so the application resolution is the same one.
