### ISSUE TITLE
Feature Request: Add a possibility to install missing binaries

### ISSUE THREAD

**Issue by breml** [marcosnils/bin#57]
I would like to have the possibility to copy the `.bin/config.json` to an other system, download `bin` and run something like `bin ensure` to download and install all the binaries listed in `.bin/config.json` (in the version specified).

Currently, `bin list` is able to detect missing binaries, but from what I can tell, there is no way to fix the *broken* state.

**Comment by marcosnils** [comment]
yes! I had the idea that I already had an issue for this but seems like I never created it. Would you like to give it a try? 
Should be relatively simple to implement.
