### ISSUE TITLE
Use plain repo name for binary

### ISSUE THREAD

**Issue by sirlatrom** [marcosnils/bin#6]
Installing bin using bin yields a binary called `bin_0.0.1_Linux_x86_64`. However, installing a binary from a docker image yields a script called e.g. `terraform`.

If it were possible to either strip the arch/os details from the downloaded binary name, or simply to use the last segment of the repo name, it would remove the need for renaming the binary after download, or for explicitly choosing the download path in the install command.

**Comment by marcosnils** [comment]
> If it were possible to either strip the arch/os details from the downloaded binary name, or simply to use the last segment of the repo name, it would remove the need for renaming the binary after download, or for explicitly choosing the download path in the install command.

bin supports to install binaries in a specific path like `bin install <ur> [path]`. So you can do something like `bin install github.com/marcosnils/bin ~/SOME_DIR_IN_PATH/bin`.

Having said that, what you suggest could be done, the thing is that each repo publishes with a different naming convention and "i think" it's going to be difficult to come up with a global stripping. One feature that I want to implement is to do `bin install <url> [filename]` and make bin download the asset with the `filename` name in the default configured folder.

**Comment by sirlatrom** [comment]
Since you have _some_ level of magic that finds a compatible binary from a multi-arch/os release, I suppose that if you've identified the right one you would also be able to use its shorter name when creating the binary?

I also like the idea of simply giving the `[filename]` argument, although if it could be avoided in some cases then it would be even better.

**Comment by marcosnils** [comment]
> Since you have _some_ level of magic that finds a compatible binary from a multi-arch/os release

This is easier since it's only matching words regardless of the filename format. For example `bin_amd64_linux` would be easy to macth and stripe. But some projects release things like `bin_v1_amd64_linux_whatever` and in that case it's more difficult to detect what the binary  name should be.

It still could be done, we just need to find a nice way to do it :)

**Comment by sirlatrom** [comment]
> This is easier since it's only matching words regardless of the filename format. For example `bin_amd64_linux` would be easy to macth and stripe. But some projects release things like `bin_v1_amd64_linux_whatever` and in that case it's more difficult to detect what the binary  name should be.

In my opinion it would be nice enough if the first easy format is matched and that leads to the binary called `bin`. I suppose it's goreleaser or gox that give the most common file names?

**Comment by marcosnils** [comment]
> In my opinion it would be nice enough if the first easy format is matched and that leads to the binary called `bin`. I suppose it's goreleaser or gox that give the most common file names?

SGTM as a first approach. I'll craft a first approach :)

**Comment by sirlatrom** [comment]
Perhaps a list of well-known possible variations could be iterated through, or alternatively rather than matching a specific name, if you can "grep" your way to a single result, the one that matches the most arch/os variables will get the highest score and be the best bet?
