### ISSUE TITLE
Add linting

### ISSUE THREAD

**Issue by marcosnils** [marcosnils/bin#62]
Bin could use some linting :cupid:

**Comment by sirlatrom** [comment]
Some linting done in in #63

**Comment by breml** [comment]
I recommend [golangci-lint](https://golangci-lint.run/) for linting Go projects.

This linter supports a large set of different linters and one can configure the linting according to the needs (and personal preference). With the default settings, there are currently quite some issues listed. Most of them are related to errors not being checked and unused code.

**Comment by breml** [comment]
And if you want to go more strict on the source code formatting, I recommend `gofumpt` (also part of `gopls`, it can be enabled as default formatting in e.g. vs code Go plugin).

```shell
bin install github.com/mvdan/gofumpt
gofumpt -w -s -l .
```
