### ISSUE TITLE
Feature Request: Use `XDG Base Directory Specification` for the configuration directory

### ISSUE THREAD

**Issue by rverst** [marcosnils/bin#77]
To avoid cluttering the users $HOME with configuration files/directories I suggest the implementation of the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).

**Comment by marcosnils** [comment]
Thx for adding this :pray:

**Comment by breml** [comment]
I like this as well and I look forward to move `~/.bin` to `$HOME/.config/bin`.
