### ISSUE TITLE
Bug: can't find correct asset for k3sup

### ISSUE THREAD

**Issue by drzero42** [marcosnils/bin#96]
Bin version: 0.5.2
OS: Ubuntu 20.04 x86_64

What happened: Trying to install [k3sup](https://github.com/alexellis/k3sup) results in bin wanting to grab the arm64 asset
How to reproduce: `bin install github.com/alexellis/k3sup`
Output: 
```
$ bin install -f --debug github.com/alexellis/k3sup
   • debug logs enabled       
   • Config directory is: /home/abo/.config/bin
   • Download path set to /home/abo/.local/bin
   • Getting latest release for alexellis/k3sup
   • Removing k3sup.sha256 (URL https://github.com/alexellis/k3sup/releases/download/0.10.2/k3sup.sha256) with score 1 lower than 6
   • Removing k3sup.exe.sha256 (URL https://github.com/alexellis/k3sup/releases/download/0.10.2/k3sup.exe.sha256) with score 1 lower than 6
   • Removing k3sup.exe (URL https://github.com/alexellis/k3sup/releases/download/0.10.2/k3sup.exe) with score 1 lower than 6
   • Removing k3sup-darwin.sha256 (URL https://github.com/alexellis/k3sup/releases/download/0.10.2/k3sup-darwin.sha256) with score 1 lower than 6
   • Removing k3sup-darwin (URL https://github.com/alexellis/k3sup/releases/download/0.10.2/k3sup-darwin) with score 1 lower than 6
   • Removing k3sup-armhf.sha256 (URL https://github.com/alexellis/k3sup/releases/download/0.10.2/k3sup-armhf.sha256) with score 1 lower than 6
   • Removing k3sup-armhf (URL https://github.com/alexellis/k3sup/releases/download/0.10.2/k3sup-armhf) with score 1 lower than 6
   • Keeping k3sup-arm64.sha256 (URL https://github.com/alexellis/k3sup/releases/download/0.10.2/k3sup-arm64.sha256) with highest score 6
   • Keeping k3sup-arm64 (URL https://github.com/alexellis/k3sup/releases/download/0.10.2/k3sup-arm64) with highest score 6
   • Removing k3sup (URL https://github.com/alexellis/k3sup/releases/download/0.10.2/k3sup) with score 1 lower than 6

Multiple matches found, please select one:

 [1] k3sup-arm64
 [2] k3sup-arm64.sha256
 Select an option: 
```

The problem here is that the author of k3sup has chosen to leave out the arch from the name of the asset meant for Linux x86_64. Given that Linux x86_64 is likely to be the most common, would it be possible to have bin to fallback assets without a specified arch as being Linux x86_64?

**Comment by sirlatrom** [comment]
If I understand correctly from previous issues of this sort, I believe we'd normally say that this is an issue with the repo rather than with `bin`, and so we cannot really solve for all those variations. @marcosnils WDYT?

**Comment by marcosnils** [comment]
> If I understand correctly from previous issues of this sort, I believe we'd normally say that this is an issue with the repo rather than with `bin`, and so we cannot really solve for all those variations. @marcosnils WDYT?

Yep, I guess we need to implement #95 to unblock these situations momentarily. I'll try to craft something today since it's an easy fix. 

I'd also try pining @alexellis since he might be willing to change the amd64 version to include the architecture to make that file consistent with the other release assets.

**Comment by drzero42** [comment]
@marcosnils I agree that I should try asking @alexellis to change the naming of assets in the future. I just wanted to test the waters on whether anything could be done on the `bin` side of things, as something like this could also be a problem with other repos, where it is less likely that the maintainer will want to change anything.
From my side, this is enough of an answer, so it could probably just be closed and the points regarding skipping dialogs can be tracked in #95 :)
